[package]
name = "cli"
version = "0.0.1"
authors = ["Tobias Raatiniemi <raatiniemi@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.20" }
env_logger = { version = "0.11.1" }
clap = { version = "4.2.5", features = ["derive"] }
json = "0.12.4"
regex = "1.8.1"
tempdir = "0.3.7"
