[package]
name = "cli"
version = "0.0.1"
authors = ["Tobias Raatiniemi <raatiniemi@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.17" }
env_logger = { version = "0.10.0" }
clap = "2.33.3"
json = "0.12.4"
regex = "1.4.5"
tempdir = "0.3.7"
