[package]
name = "app"
version = "0.0.1"
authors = ["Tobias Raatiniemi <raatiniemi@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
json = "0.12.4"
regex = "1.4.5"
tempdir = "0.3.7"
rayon = "1.5.1"
opentelemetry = { version = "0.14.0" }
opentelemetry-jaeger = { version = "0.13.0" }
